### ISSUE TITLE
expo bare work flow 에서 toss 앱 링크 테스트 

### ISSUE THREAD

**Issue by HYJ29** [heartright-co/expo-test-module#2]
- [x] bare work flow 이해 
- [x] deploy 차이점 알아보기 
- [x] toss 앱 링크 테스트
- [x] build 해보기 
- [x] toss 링크후 돌아와서 flow 처리

**Comment by byyoungjin** [comment]
## bare workflow 이해 
(전반적으로 stack overflow 자료는 outdate 된것들이 있는것같다. 
bare 에서도  [build , submit](https://blog.expo.io/expo-application-services-eas-build-and-submit-fc1d1476aa2e) 이 가능하다 ! -> 다만 구독이 필요함 ) 
### 1. [bare workflow vs react-native ](https://stackoverflow.com/questions/61723372/what-is-the-difference-between-react-native-cli-and-expo-with-bare-workflow#:~:text=Bare%20workflow%20gives%20you%20more,projects%20and%20any%20native%20code.) :

bare workflow는
기본적으로 RN 과 동일하다. 
차이점이라면 
RN 에 비해  조금더 configuration 되어있다. 
대표적으로 expo 에서 제공하는 module 을 사용할 수있게, [react-native-unimodules](https://docs.expo.io/bare/installing-unimodules/) 이 setup 되어있음. 


그외에도 expo 를 쓰게 되면 같이 들어가는 facebook 모듈등의 expo 특징이 그대로 들어간다. 
다만 
1. build 서비스 
2. app.json 을 통한 편한 configuration 
은 managed 에서만 제공한다. 

### 2. 추가정보 
[RN cli vs Expo cli](https://stackoverflow.com/questions/54862388/what-is-the-difference-between-expo-cli-and-react-native-cli)
[react-native build app example](https://www.youtube.com/watch?v=0-S5a0eXPoc)

여전히 expo-cli 를 개발에 사용할 수있다. 다만, expo module 부분만 정상 작동하고 expo SDK 에 포함되지 않은 모듈은 error 가뜬다. 하지만 이것도 조절할수있다. https://docs.expo.io/bare/using-expo-client/
위에서 .expo.js 등의 extension 이 더이상 제공되지 않음 https://github.com/expo/fyi/blob/master/expo-extension-migration.md


[why not expo](https://docs.expo.io/introduction/why-not-expo/)



### 3. 라이브러리사용 
https://docs.expo.io/bare/using-libraries/


### 4. 헷갈리던것들 
create-react-native-app ->[ expo 에서 제공한다. 그래서 bare-work-flow 를 생성한다. ](https://github.com/expo/create-react-native-app)
(expo init -> bare 와 같은 효과?)
react-native init -> pure react-native 

react-native 공식 페이지에서도 expo 를 적극적으로 사용하고 있다. 
https://reactnative.dev/docs/environment-setup


### 5. Native module 이해하기 , 익숙해지기 
[native module 만들어보기](https://reactnative.dev/docs/native-modules-intro )


### 6. expo publish 할때 , 내 개인 아이디인 eric_ha 가 아니라 pnuu 계정으로하기 
expo init 자체를 pnuu 아이디로 해야한다. 
~~아니면 publish 하기전에 다음과 같이 수정해야한다.~~
다른계정으로  publish, build 하면 자동으로 수정된다. 
```
🚀 expo-updates (​https://github.com/expo/expo/blob/master/packages/expo-updates/README.md​) has been configured in your project. If you publish this project under a different user account than eric_ha, you'll need to update the configuration in Expo.plist and AndroidManifest.xml before making a release build.
```



https://reactnative.dev/docs/native-modules-setup

**Comment by byyoungjin** [comment]
## deploy 차이점 알아보기 
기본은 rn 이랑 같을듯 
https://reactnative.dev/docs/signed-apk-android
https://reactnative.dev/docs/publishing-to-app-store


https://medium.com/@klpdjolanta/13-steps-to-deploying-react-native-android-app-to-google-play-store-using-android-studio-c2ec0c434145

**Comment by byyoungjin** [comment]
## toss 앱 link test 

https://www.figma.com/file/oomj2yGjVvOfqetp3KwRVL/module-test?node-id=0%3A1

1. toss scheme 참고 ->  toss 측에 확실히 알아봐야함 
https://tossbutton.docs.apiary.io/#reference

2. toss app 이 없을 경우, toss 앱 설치 페이지로 이동 
ios
https://stackoverflow.com/questions/433907/how-to-link-to-apps-on-the-app-store#:~:text=Right%2Dclick%20or%20control%2Dclick,item%20in%20the%20App%20Store.

android
https://developer.android.com/distribute/marketing-tools/linking-to-google-play

특정 앱의 아이디를 어떻게 아나
https://abhimuralidharan.medium.com/how-to-find-the-bundle-id-of-an-ios-app-in-appstore-using-itunes-lookup-api-6a9bdaff102a

https://learn.apptentive.com/knowledge-base/finding-your-app-store-id/#:~:text=An%20iOS%20application's%20store%20ID,id284708449%20the%20ID%20is%3A%20284708449%20.

[토스 설치 링크 구글에 검색하니 바로나옴](https://www.google.com/search?q=%ED%86%A0%EC%8A%A4+%EC%84%A4%EC%B9%98+%EB%A7%81%ED%81%AC&oq=%ED%86%A0%EC%8A%A4+%EC%84%A4%EC%B9%98+%EB%A7%81%ED%81%AC&aqs=chrome..69i57j0j0i30l2j0i8i30l3.4225j0j7&sourceid=chrome&ie=UTF-8)

deep link
https://docs.expo.io/guides/linking/


### toss 에서 BOA  , JP 모건 은행 이용가능 
[토스 특징들](https://blog.toss.im/2020/07/01/toss/guide/toss-transfer/)

**Comment by byyoungjin** [comment]
## issue on https://github.com/heartright-co/expo-test-module/issues/2#issuecomment-815413702
toss 버튼 누르기 -> toss 이동 -> 앱돌아오면 afterToss page 로 네이게이션, 버튼누르면 다른페이지. 

- [x] AppState 이용해서 구현하는데, eventListener 잘 처리하기

**Comment by byyoungjin** [comment]
## ToDo 
1. SKStoreProductViewController  이용하면 앱내에서 설치페이지 갈수있음 
[관련 rn 페키지 ](https://www.npmjs.com/package/react-native-store-view)

**Comment by byyoungjin** [comment]
## 공유할 내용 
1. expo heartright org 관하여 
org 에 속하면 바로 build 를 heartright 에 올릴 수있을 줄 알았는데, 
유료feature 였다. https://expo.io/pricing
expo 유료 feature 를 이용하면, 
위 feature 와 함께, 
기존에는 build 가 빨라지고, expo 에서 trouble shooting 을 우선적으로 처리해주는 장점뿐이었는데, 
최근 EAS build 라고해서 기존에 managed 에서만 지원했던, expo build, store submit , update over the air 
와 같은 기능을 지원하는듯함..  
있으면 정말 편하고 재밌을것 같긴한데, 
없어도 사실 크게 상관은 없는 사항이라  (적은 인원일땐 없어도 상관없을듯하다) 

그냥 회사 본  계정으로 로그인해서 build 하면 된다. 

update over the air 가 정확히 어떤식으로 지원해주는지만 나중에 알아볼 필요가 있을듯 

https://docs.expo.io/versions/latest/config/app/
![image](https://user-images.githubusercontent.com/44938459/114010274-e63dda00-989e-11eb-8262-73f752d00516.png)

2. 토스 해외송금은 가능, 해외에서 국내유저 송금은 안될듯. 
은행목록에 BOA, Morgan 등이 있어서 해외 송금도 문제는 없을듯. [근데 국내통신사를 통해 개통한 유저만 토스 사용가능하다고함](https://blog.toss.im/2018/09/06/toss/guide/toss-true-false-best-7/)
